name: Microservices Continuous Deployment with Github Actions
on:
  push:
    branches: 
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4   
    - name: Login to docker hub
      uses: docker/login-action@v3.7.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        
    - name: Setup Java 21
      uses: actions/setup-java@v5
      with:
        distribution: 'adopt'
        java-version: '21'
    
    - name: Build Eureka Naming Server Docker Image
      working-directory: ./naming-server
      run: mvn spring-boot:build-image -DskipTests

    - name: Build API Gateway Docker Image
      working-directory: ./api-gateway
      run: mvn spring-boot:build-image -DskipTests

    - name: Build Book Service
      working-directory: ./book-service
      run: mvn clean package

    - name: Build Exchange Service
      working-directory: ./exchange-service
      run: mvn clean package

